default_language_version:
  node: '14.13.0'
repos:
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
        exclude_types: [html]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@6.8.0
          - typescript@4.2.3
          - '@typescript-eslint/eslint-plugin@4.18.0'
          - '@typescript-eslint/parser@4.18.0'
          - eslint-config-prettier@6.5.0
          - eslint-plugin-import@2.20.0
          - eslint-plugin-react@7.18.0
          - eslint-plugin-react-hooks@2.3.0
          - eslint-plugin-jest@23.6.0
          - eslint-plugin-deprecate@0.7.0
          - eslint-plugin-babel@5.3.1
          - escope@3.6.0

        # remove default javascript-only filter so we can lint typescript
        # https://github.com/pre-commit/mirrors-eslint/blob/master/.pre-commit-hooks.yaml
        types: []
        files: '.*\.(jsx|ts|tsx)$'
        args: ['--parser-options=project:./tsconfig.json', '--cache']
